#!/usr/bin/env bash
set -euo pipefail

# Setup test .env file
# Usage: ./scripts/setup-test-env.sh [password]

PASSWORD="${1:-test-password}"

echo "Setting up test .env file..."
echo "Password: $PASSWORD"
echo ""

# Generate password hash
echo "Generating password hash..."
HASH=$(go run scripts/generate-password-hash.go "$PASSWORD")
if [ $? -ne 0 ]; then
    echo "Failed to generate password hash"
    exit 1
fi

# Generate session secret
echo "Generating session secret..."
SECRET=$(openssl rand -base64 32)
if [ $? -ne 0 ]; then
    echo "Failed to generate session secret"
    exit 1
fi

# Create .env file
cat > .env << EOF
# Test Environment Variables
# Generated by setup-test-env.sh
# Password: $PASSWORD

APP_PORT=8000
TELEGRAM_BOT_TOKEN=

# Authentication
AUTH_PASSWORD_HASH='$HASH'
AUTH_SESSION_SECRET='$SECRET'
AUTH_SESSION_MAX_AGE=86400
EOF

echo "✓ Created .env file"
echo ""
echo "To use:"
echo "  1. Start server: go run ./cmd/app"
echo "  2. Login with password: $PASSWORD"
echo "  3. Test URL: http://localhost:8000/"
echo ""
